# COLUMSCREATOR
Este Notebook  genera columnas a partir de la información de las columnas rankID y taxon, para que sea posible unir varios documentos, sin perder la jerarquia del orden taxonomico con el que están generados, los documentos iniciales provienen de un análisis de secunecias con Mothur y la base de datos SILVA.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

En función de la hoja que se quiera modificar del excel cambio sheet_name o bien pongo 'SUP' o pongo'AIRE'

In [2]:
taxonesaire=pd.read_excel("Diversidad Hospital_UN_trated_Hpy.xlsx", sheet_name='AIRE')

In [3]:
taxonesaire

,taxlevel,rankID,taxon,daughterlevels,total,EH-A,ICU-CO-A,ICU-TR-A,ICU-PR1-A,OR-A,CO-A,TR-A,PR-A,ICU-PR2-A
0,0,0,Root,1,302197,24726,45269,34453,15626,25580,43204,33321,57900,22118
1,1,0.1,Bacteria,21,302197,24726,45269,34453,15626,25580,43204,33321,57900,22118
2,2,0.1.1,Acidobacteria,5,1280,0,0,0,122,0,0,0,0,1158
3,3,0.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0
4,4,0.1.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,4,0.1.21.1.4,Verrucomicrobiales,2,4,0,0,0,4,0,0,0,0,0
825,5,0.1.21.1.4.1,Rubritaleaceae,1,3,0,0,0,3,0,0,0,0,0
826,6,0.1.21.1.4.1.1,Luteolibacter,0,3,0,0,0,3,0,0,0,0,0
827,5,0.1.21.1.4.2,Verrucomicrobiaceae,1,1,0,0,0,1,0,0,0,0,0
828,6,0.1.21.1.4.2.1,Verrucomicrobiaceae_uncultured,0,1,0,0,0,1,0,0,0,0,0

In [4]:
#taxonesaire['phylo'] = np.nan#creo unacolumna

In [5]:
taxonesaire.head()

,taxlevel,rankID,taxon,daughterlevels,total,EH-A,ICU-CO-A,ICU-TR-A,ICU-PR1-A,OR-A,CO-A,TR-A,PR-A,ICU-PR2-A
0,0,0,Root,1,302197,24726,45269,34453,15626,25580,43204,33321,57900,22118
1,1,0.1,Bacteria,21,302197,24726,45269,34453,15626,25580,43204,33321,57900,22118
2,2,0.1.1,Acidobacteria,5,1280,0,0,0,122,0,0,0,0,1158
3,3,0.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0
4,4,0.1.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0

In [6]:
fila = taxonesaire.iloc[3]

In [7]:
fila

taxlevel                                   3
rankID                               0.1.1.1
taxon             Acidobacteria_unclassified
daughterlevels                             1
total                                      5
EH-A                                       0
ICU-CO-A                                   0
ICU-TR-A                                   0
ICU-PR1-A                                  5
OR-A                                       0
CO-A                                       0
TR-A                                       0
PR-A                                       0
ICU-PR2-A                                  0
Name: 3, dtype: object

In [8]:
lista_rankID= fila.rankID.split(sep='.')

In [9]:

lista_rankID

['0', '1', '1', '1']

In [10]:
type(lista_rankID)

list

In [11]:
len(lista_rankID)

4

In [12]:
 level=2 # hago un contador

In [13]:
lista_selector=lista_rankID[0:level]

In [14]:
 selector='.'.join(lista_selector)

In [15]:
df = taxonesaire

In [16]:
if len(lista_rankID[0:level]) < level:
     nombre_selector=np.nan
else:
    nombre_selector=df[df.rankID==selector].taxon 
    nombre_selector=nombre_selector.values[0]

In [17]:
nombre_selector=df[df.rankID==selector].taxon #dataframe de una sola celda
nombre_selector=nombre_selector.values[0] #no es un dataframe es el valor de una celda

In [18]:
def column_creator(fila, level, df):
    """
    fila = 
    """
    try:
        lista_rankID= fila.rankID.split(sep='.')
        lista_selector=lista_rankID[0:level]
        selector='.'.join(lista_selector)
        nombre_selector=df[df.rankID==selector].taxon 
        if len(lista_rankID[0:level]) < level:
             nombre_selector=np.nan
        else:
            nombre_selector=nombre_selector.values[0]
    except Exception:
        nombre_selector=np.nan
    return nombre_selector

In [19]:
column_creator(fila, 2, taxonesaire)

'Bacteria'

In [20]:
taxonesaire.apply(column_creator,axis=1, args=(2,taxonesaire))

0           NaN
1      Bacteria
2      Bacteria
3      Bacteria
4      Bacteria
         ...
824    Bacteria
825    Bacteria
826    Bacteria
827    Bacteria
828    Bacteria
Length: 829, dtype: object

In [21]:
fila

taxlevel                                   3
rankID                               0.1.1.1
taxon             Acidobacteria_unclassified
daughterlevels                             1
total                                      5
EH-A                                       0
ICU-CO-A                                   0
ICU-TR-A                                   0
ICU-PR1-A                                  5
OR-A                                       0
CO-A                                       0
TR-A                                       0
PR-A                                       0
ICU-PR2-A                                  0
Name: 3, dtype: object

In [22]:
taxonesaire['dominio'] = taxonesaire.apply(column_creator,axis=1, args=(2,taxonesaire))

In [23]:
taxonesaire['phylo'] = taxonesaire.apply(column_creator,axis=1, args=(3,taxonesaire))

In [24]:
taxonesaire['clase'] = taxonesaire.apply(column_creator,axis=1, args=(4,taxonesaire))

In [25]:
taxonesaire['orden'] = taxonesaire.apply(column_creator,axis=1, args=(5,taxonesaire))

In [26]:
taxonesaire['familia'] = taxonesaire.apply(column_creator,axis=1, args=(6,taxonesaire))

In [27]:
taxonesaire['genero'] = taxonesaire.apply(column_creator,axis=1, args=(7,taxonesaire))

In [28]:
taxonesaire.head(50)

,taxlevel,rankID,taxon,daughterlevels,total,EH-A,ICU-CO-A,ICU-TR-A,ICU-PR1-A,OR-A,CO-A,TR-A,PR-A,ICU-PR2-A,dominio,phylo,clase,orden,familia,genero
0,0,0,Root,1,302197,24726,45269,34453,15626,25580,43204,33321,57900,22118,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0.1,Bacteria,21,302197,24726,45269,34453,15626,25580,43204,33321,57900,22118,Bacteria,NaN,NaN,NaN,NaN,NaN
2,2,0.1.1,Acidobacteria,5,1280,0,0,0,122,0,0,0,0,1158,Bacteria,Acidobacteria,NaN,NaN,NaN,NaN
3,3,0.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteria_unclassified,NaN,NaN,NaN
4,4,0.1.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteria_unclassified,Acidobacteria_unclassified,NaN,NaN
5,5,0.1.1.1.1.1,Acidobacteria_unclassified,1,5,0,0,0,5,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteria_unclassified,Acidobacteria_unclassified,Acidobacteria_unclassified,NaN
6,6,0.1.1.1.1.1.1,Acidobacteria_unclassified,0,5,0,0,0,5,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteria_unclassified,Acidobacteria_unclassified,Acidobacteria_unclassified,Acidobacteria_unclassified
7,3,0.1.1.2,Acidobacteriia,2,1216,0,0,0,58,0,0,0,0,1158,Bacteria,Acidobacteria,Acidobacteriia,NaN,NaN,NaN
8,4,0.1.1.2.1,Acidobacteriales,2,24,0,0,0,24,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,NaN,NaN
9,5,0.1.1.2.1.1,Acidobacteriaceae_(Subgroup_1),4,21,0,0,0,21,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriaceae_(Subgroup_1),NaN
10,6,0.1.1.2.1.1.1,Acidipila,0,9,0,0,0,9,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriaceae_(Subgroup_1),Acidipila
11,6,0.1.1.2.1.1.2,Bryocella,0,2,0,0,0,2,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriaceae_(Subgroup_1),Bryocella
12,6,0.1.1.2.1.1.3,Granulicella,0,3,0,0,0,3,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriaceae_(Subgroup_1),Granulicella
13,6,0.1.1.2.1.1.4,Acidobacteriaceae_(Subgroup_1),0,7,0,0,0,7,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriaceae_(Subgroup_1),Acidobacteriaceae_(Subgroup_1)
14,5,0.1.1.2.1.2,Acidobacteriales_unclassified,1,3,0,0,0,3,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriales_unclassified,NaN
15,6,0.1.1.2.1.2.1,Acidobacteriales_unclassified,0,3,0,0,0,3,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Acidobacteriales,Acidobacteriales_unclassified,Acidobacteriales_unclassified
16,4,0.1.1.2.2,Solibacterales,1,1192,0,0,0,34,0,0,0,0,1158,Bacteria,Acidobacteria,Acidobacteriia,Solibacterales,NaN,NaN
17,5,0.1.1.2.2.1,Solibacteraceae_(Subgroup_3),2,1192,0,0,0,34,0,0,0,0,1158,Bacteria,Acidobacteria,Acidobacteriia,Solibacterales,Solibacteraceae_(Subgroup_3),NaN
18,6,0.1.1.2.2.1.1,Bryobacter,0,32,0,0,0,32,0,0,0,0,0,Bacteria,Acidobacteria,Acidobacteriia,Solibacterales,Solibacteraceae_(Subgroup_3),Bryobacter
19,6,0.1.1.2.2.1.2,Solibacteraceae_(Subgroup_3),0,1160,0,0,0,2,0,0,0,0,1158,Bacteria,Acidobacteria,Acidobacteriia,Solibacterales,Solibacteraceae_(Subgroup_3),Solibacteraceae_(Subgroup_3)
20,3,0.1.1.3,Blastocatellia_(Subgroup_4),1,46,0,0,0,46,0,0,0,0,0,Bacteria,Acidobacteria,Blastocatellia_(Subgroup_4),NaN,NaN,NaN
21,4,0.1.1.3.1,Blastocatellales,1,46,0,0,0,46,0,0,0,0,0,Bacteria,Acidobacteria,Blastocatellia_(Subgroup_4),Blastocatellales,NaN,NaN
22,5,0.1.1.3.1.1,Blastocatellaceae,2,46,0,0,0,46,0,0,0,0,0,Bacteria,Acidobacteria,Blastocatellia_(Subgroup_4),Blastocatellales,Blastocatellaceae,NaN
23,6,0.1.1.3.1.1.1,Blastocatella,0,29,0,0,0,29,0,0,0,0,0,Bacteria,Acidobacteria,Blastocatellia_(Subgroup_4),Blastocatellales,Blastocatellaceae,Blastocatella
24,6,0.1.1.3.1.1.2,Blastocatellaceae,0,17,0,0,0,17,0,0,0,0,0,Bacteria,Acidobacteria,Blastocatellia_(Subgroup_4),Blastocatellales,Blastocatellaceae,Blastocatellaceae
25,3,0.1.1.4,Holophagae,1,4,0,0,0,4,0,0,0,0,0,Bacteria,Acidobacteria,Holophagae,NaN,NaN,NaN
26,4,0.1.1.4.1,Subgroup_7,1,4,0,0,0,4,0,0,0,0,0,Bacteria,Acidobacteria,Holophagae,Subgroup_7,NaN,NaN
27,5,0.1.1.4.1.1,Subgroup_7_fa,1,4,0,0,0,4,0,0,0,0,0,Bacteria,Acidobacteria,Holophagae,Subgroup_7,Subgroup_7_fa,NaN
28,6,0.1.1.4.1.1.1,Subgroup_7_ge,0,4,0,0,0,4,0,0,0,0,0,Bacteria,Acidobacteria,Holophagae,Subgroup_7,Subgroup_7_fa,Subgroup_7_ge
29,3,0.1.1.5,Subgroup_6,2,9,0,0,0,9,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,NaN,NaN,NaN
30,4,0.1.1.5.1,Subgroup_6_or,1,7,0,0,0,7,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,Subgroup_6_or,NaN,NaN
31,5,0.1.1.5.1.1,Subgroup_6_fa,1,7,0,0,0,7,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,Subgroup_6_or,Subgroup_6_fa,NaN
32,6,0.1.1.5.1.1.1,Subgroup_6_ge,0,7,0,0,0,7,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,Subgroup_6_or,Subgroup_6_fa,Subgroup_6_ge
33,4,0.1.1.5.2,Subgroup_6_unclassified,1,2,0,0,0,2,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,Subgroup_6_unclassified,NaN,NaN
34,5,0.1.1.5.2.1,Subgroup_6_unclassified,1,2,0,0,0,2,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,Subgroup_6_unclassified,Subgroup_6_unclassified,NaN
35,6,0.1.1.5.2.1.1,Subgroup_6_unclassified,0,2,0,0,0,2,0,0,0,0,0,Bacteria,Acidobacteria,Subgroup_6,Subgroup_6_unclassified,Subgroup_6_unclassified,Subgroup_6_unclassified
36,2,0.1.2,Actinobacteria,7,46099,3173,10150,4256,6311,7976,2166,5213,2980,3874,Bacteria,Actinobacteria,NaN,NaN,NaN,NaN
37,3,0.1.2.1,Acidimicrobiia,3,90,0,0,0,90,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,NaN,NaN,NaN
38,4,0.1.2.1.1,Acidimicrobiia_unclassified,1,26,0,0,0,26,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Acidimicrobiia_unclassified,NaN,NaN
39,5,0.1.2.1.1.1,Acidimicrobiia_unclassified,1,26,0,0,0,26,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Acidimicrobiia_unclassified,Acidimicrobiia_unclassified,NaN
40,6,0.1.2.1.1.1.1,Acidimicrobiia_unclassified,0,26,0,0,0,26,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Acidimicrobiia_unclassified,Acidimicrobiia_unclassified,Acidimicrobiia_unclassified
41,4,0.1.2.1.2,Microtrichales,4,57,0,0,0,57,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,NaN,NaN
42,5,0.1.2.1.2.1,Iamiaceae,1,1,0,0,0,1,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Iamiaceae,NaN
43,6,0.1.2.1.2.1.1,Iamia,0,1,0,0,0,1,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Iamiaceae,Iamia
44,5,0.1.2.1.2.2,Ilumatobacteraceae,1,18,0,0,0,18,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Ilumatobacteraceae,NaN
45,6,0.1.2.1.2.2.1,Ilumatobacteraceae_uncultured,0,18,0,0,0,18,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Ilumatobacteraceae,Ilumatobacteraceae_uncultured
46,5,0.1.2.1.2.3,Microtrichales_unclassified,1,35,0,0,0,35,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Microtrichales_unclassified,NaN
47,6,0.1.2.1.2.3.1,Microtrichales_unclassified,0,35,0,0,0,35,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Microtrichales_unclassified,Microtrichales_unclassified
48,5,0.1.2.1.2.4,Microtrichales_uncultured,1,3,0,0,0,3,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Microtrichales_uncultured,NaN
49,6,0.1.2.1.2.4.1,Microtrichales_uncultured,0,3,0,0,0,3,0,0,0,0,0,Bacteria,Actinobacteria,Acidimicrobiia,Microtrichales,Microtrichales_uncultured,Microtrichales_uncultured

In [29]:
lista_rankID[0:1000]

['0', '1', '1', '1']

## Crear excel
En función de si quiero generar un excel o si quiero añadir una hoja, elijo una opción u otra, y además hay que tener en cuenta el nobre de la hoja el sheet name!!!

In [30]:
#taxonesaire.to_excel('Diversidad Hospital_columscreator_Hpy.xlsx',index=False, sheet_name='AIRE')

## Introducir una hoja nueva en un excel ya creado

In [31]:

with pd.ExcelWriter('Diversidad Hospital_columscreator_Hpy.xlsx', engine = 'openpyxl', mode='a') as writer:
    taxonesaire.to_excel(writer,index=False, sheet_name='AIRE')